package main

var phrases = [...]string{
	"C'est pour ça que je fais de l'infrastructure as code",
	"Openldap !",
	"Tu sais combiens j'ai de clé ssh ?",
	"Linus Torwald il a dev un bout du kernel linux",
	"Open source ça veut pas dire libre.",
	"Je vais faire un tour à vélo",
	"Ca joue ou bien ?",
	"VScodium",
	"Non, il y a des trackers...",
	"Tu fait une note de frais à EduVaud",
	"Un projet open-source n'es pas forcément libre, ça dépend...",
	"J'ai un role Ansible pour mapper mes interfaces externes sur les ports non-routables de mon proxy a la maison.",
	"Nous à l'EPFL on avait un forwarder DNS open source qui tournait en h24 sur un noyau bridé H2 pour empecher le nettoyage dynamique des caches stockés en local.",
	"C'est à cause du noyau te ton kernel qui est en 4.14/42 !",
	"Parce que le protocole http refuse que ton ip soit non-masquée par un provider, du coup coup l'API prend le dessus et tu perds toutes tes données.",
	"C’est pas ce le logo de BASH.",
	"Il est posix compatible le Bourne Shell.",
	"Avec BASH on peut aussi !",
	"Le chemin absolu",
	"Il faut mettre un she-bang ",
	"Man c'est génial.",
	"RTFM...",
	"Il faut, c'est important.",
	"Ansible !",
	"42, école 42",
	"Tu sais que j'ai Amazon à la maison avec S3 ?",
	"Eh j'ai fait du OpenLdap tout le weekend !",
	"C'étais à la benne ! Moi je me sert",
	"J'ai démonter tout mon vélo pour le nettoyer tip top  hier !",
	"Je signe tout mes commit !",
	"Tu as une clé GPG ?",
	"Avec Biscaro on chiffre tout nos emails",
	"Notion c'est pas du Markdown",
	"Rien de mieux qu'un Kangoo diesel",
	"Dnsmaq c'est pour la maison pas les entreprises",
	"VMware c'est de la merde",
	"Regarde mon gestionnaire de mot de passe es tout en ligne de commande !",
	"Sur mon switch Aruba à la maison c'est pas la même chose.",
	"Infomaniak c'est la meilleur boite.",
	"J'ai un Vagrant pour faire une full stack lamp !",
	"C'est sur mon Gitlab a la Maison...",
	"Utilise un vrais OS, genre Debian 11.5 Bullseye avec la dernier version qui es sortie le mois passé. En plus c'est libre, Open-source et tu es pas traqué par rapport a ton Windows de M propriétaire",
	"Thunderbird c'est mieux que Outlook.",
	"Les port IMAP du CPNV sont fermer.",
	"On peux pas ce connecté avec Thunderbird.",
	"Utilise VI pas nano...",
	"pas de sucre en plus de ceux qui sont dans le fruit.",
	"Maseltov, comme ils disent...",
	"Rend ça Open-source",
	"Mes clés RSA sont en 4096",
	"Terraform !",
	"KVM",
	"Tu veux mon Vagrant?",
	"KVM c'est mieux que VirtualBOX",
	"Il faut soutiré les infos",
	"je sais pas mais avec VIM",
	"Les workaround c'est ma vie",
	"ça fait plusieur année que j'ai pas eu d'interation avec une fille",
	"il faut touiller la config"
}
